# Generated by Django 2.0.6 on 2018-07-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddImage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
